language: php
sudo: false
git:
  submodules: false
cache:
  directories:
    - vendor
    - $HOME/.composer
php:
  - 7.2
  - 7.3
  - 7.4
install:
  - export PATH=$PATH:~/.composer/vendor/bin
  - which php-cs-fixer || composer global require fabpot/php-cs-fixer
  - composer install
script:
  - vendor/bin/phpunit
  - vendor/bin/php-cs-fixer fix --dry-run -v --diff
  - vendor/bin/psalm
