on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: |
          composer global require friendsofphp/php-cs-fixer
          composer --no-interaction install
      - name: PHP CS fix
        run: vendor/bin/php-cs-fixer fix --dry-run -v --diff
      - name: PHP unit tests
        run: vendor/bin/phpunit
      - name: Psalm linter
        run: vendor/bin/psalm
